obstacle_range: 2.5
raytrace_range: 3.0
robot_base_frame: base_link
footprint: [[-0.4,-0.29], [-0.4,0.29], [0.4,0.29], [0.4,-0.29]]
#footprint_inflation: 0.01
#robot_radius: 0.175
inflation_radius: 1.0
cost_scaling_factor: 3.0
map_type: costmap
#transform_tolerance: 1
observation_sources: laser_scan_sensor   #realsense_scan_sensorB   realsense_scan_sensorA
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
