global_frame: map
robot_base_frame: base_link

obstacle_range: 2.5
raytrace_range: 3.0 
#robot_radius: 0.275
#footprint: [[-0.4,-0.29],[-0.4,0.29],[0.4,0.29],[0.4,-0.29] ]
footprint: [[-0.4,-0.29], [-0.4,0.29], [0.4,0.29], [0.4,-0.29]]
                                                    #是否启用
observation_sources: laser_scan_sensor   #realsense_scan_sensorB   realsense_scan_sensorA
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true} 




