local_costmap:

  update_frequency:  5.0
  
  publish_frequency: 5.0
  transform_tolerance: 0.5

  static_map: false

  rolling_window: true

  width: 4.0
  height: 4.0
  resolution: 0.03   #0.05
  cost_scaling_factor: 2.75 
  inflation_radius:  0.4 #1.0
  obstacles:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
  
#  inflation:
    


