#planners:
#  - name: GlobalPlanner
#    type: global_planner/GlobalPlanner

#controllers:
#  - name: TrackingPidLocalPlanne
#    type: path_tracking_pid/TrackingPidLocalPlanne
base_global_planner: "global_planner/GlobalPlanner"            # 指定用于move_base的全局规划器插件名称
#base_global_planner:  "path_tracking_pid/TrackingPidLocalPlanne"

shutdown_costmap: false        # default false  当move_base在不活动状态时,是否关掉costmap

controller_frequency:  10 #4  #5 #2.5 #10     # default 20.0   向底盘控制移动话题cmd_vel发送命令的频率
controller_patience: 3.0 #5.0        # default 15.0   在空间清理操作执行前,控制器花多长时间等有效控制指令下发

planner_frequency:  0 #5 #1.0 #0.1      # default 0.0    全局规划操作的执行频率(Hz)。如果频率设置为0.0，则仅当收到新目标或局部规划器报告其路径堵塞时，才会重新执行规划操作。
planner_patience: 3.0 #5.0           # default 5.0    在空间清理操作执行前,留给规划器多长时间(s)来找出一条有效规划

oscillation_timeout: 5 #10.0       # default 0.0    执行恢复行为之前允许振荡的秒数
oscillation_distance: 0.2 #0.02       # default 0.5    机器人必须移动多米才能被视为没有振动



