GlobalPlanner:
  allow_unknown: false    #是否允许规划器规划穿过未知区域的路径,只设计该参数为true还不行,还要在costmap_commons_params.yaml中设置track_unknown_space参数也为false才行。
  default_tolerance: 0 #0.55 #0.35   #当设置的目的地被障碍物占据时,需要以该参数为半径寻找到最近的点作为新目的地点.
  visualize_potential: false  #是否显示从PointCloud2计算得到的势区域
  use_dijkstra:  true           #如果设置为true,将使用dijkstra算法,否则使用A*算法
  use_quadratic: true         #如果设置为true,将使用二次函数近似函数,否则使用更加简单的计算方式,这样节省硬件计算资源.
  use_grid_path: false          #如果如果设置为true,则会规划一条沿着网格边界的路径,偏向于直线穿越网格,否则将使用梯度下降算法,路径更为光滑点.
  old_navfn_behavior: false  #若在某些情况下,想让global_planner完全复制navfn的功能, 不建议设置为true.
 
  lethal_cost: 253                   #致命代价值
  neutral_cost: 66                   # 中等代价值
  cost_factor: 0.55                 # 代价地图与每个代价值相乘的因子
  
  publish_potential: true         #是否发布costmap的势函数
  orientation_mode: 0            # 如何设置每个点的方向（None = 0,Forward = 1,Interpolate = 2,ForwardThenInterpolate = 3,Backward = 4,Leftward = 5,Rightward = 6）
  orientation_window_size: 1  #根据orientation_mode指定的位置积分来得到使用窗口的方向
  