controller_frequency:  3.0
recovery_behavior_enabled:  false
clearing_rotation_allowed:  false

TrajectoryPlannerROS:
  max_vel_x: 0.8  #1
  min_vel_x: 0.05 #1

  max_vel_y:  0.0    #  zero  for  a  differential  drive  robot
  min_vel_y:  0.0
  min_in_place_vel_theta:  0.05
  escape_vel:  -0.1

  acc_lim_x: 2.5  #2.5 #0.6 #0.8 #1.0
  acc_lim_y:  0.0  #  zero  for  a  differential  drive  robot
  acc_lim_theta: 3.2  #3.2 #0.5



  holonomic_robot: false

  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance:  false #true #  # ( 默认值：false) 如果目标容差被锁定，如果机器人到达目标 xy 位置，它将简单地旋转到位，即使它在这样做时最终超出了目标容差

  pdist_scale:  0.9
  gdist_scale:  0.6
  meter_scoring:  true

  heading_lookahead: 0.525          #对不同的原地旋转轨迹进行评分时，以米为单位向前看多远
  heading_scoring: false      #是否根据机器人朝向路径的方向或与路径的距离进行评分
  heading_scoring_timestep: 0.8

  occdist_scale: 0.1 #0.3 #0.2 # default 0.01   定义控制器躲避障碍物的程度
  oscillation_reset_dist:  0.05
  publish_cost_grid_pc: false
  prune_plan: true

  sim_time:  1.0 #1.7  #规划时需要考虑未来多长时间，结合dwa
  sim_granularity: 0.025
  angular_sim_granularity: 0.025

  vx_samples: 10 #20
  vy_samples: 0 # 差速轮机器人无Y方向速度，取0
  vtheta_samples: 20 #60
#controller_frequency: 10



  dwa: true #false
  simple_attractor:  false

#  meter_scoring: true
#  path_distance_bias: 32 #0.8 #2.5  #2.95 #0.8
#  goal_distance_bias: 20 #0.6 #0.6 #2.5 #0.6


  
#  oscillation_reset_dist: 0.05
  

#  global_frame_id: odom
  
  



