
robot_radius: 0.3  
#footprint: [[-0.4,-0.29], [-0.4,0.29], [0.4,0.29], [0.4,-0.29]]
obstacle_range: 2.0
raytrace_range: 3.0 

obstacle_layer:                                                      #配置障碍物图层
    enabled: true                                                       #是否启用
    max_obstacle_height: 2.0                                # default 2.0   描述障碍物的最大高度
    min_obstacle_height: 0.03                             # 描述障碍物的最小高度
#min_detect_distance: 0.25     
    z_resolution:         0.1
    z_voxels:             22  
    track_unknown_space:  true                     
#meter_scoring: true
    expected_update_rate: 0
    combination_method: 1
    observation_sources: laser_scan_sensor  realsense_scan_sensorB   #realsense_scan_sensorA
    laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true} 
#    realsense_scan_sensorA: {sensor_frame: d435_L_link, data_type: LaserScan, topic: /realsense_scan1, marking: true, clearing: true,inf_is_valid: true ,observation_keep_time: 0.0}
    realsense_scan_sensorB: {sensor_frame: d435_R_link, data_type:  LaserScan, topic: /realsense_scan2, marking: true, clearing: true,inf_is_valid: true,observation_keep_time: 0.0}
 
#camera_layer:
#    enabled:              true
#    max_obstacle_height:  2.2
#    origin_z:             0.0
#    z_resolution:         0.1
#    z_voxels:             22
#    unknown_threshold:    15
#    mark_threshold:       0
# #   combination_method:   1
# #   track_unknown_space:  true    #true needed for disabling global path planning through unknown space
# #   obstacle_range: 2.5
# #   raytrace_range: 3.0
# #   publish_voxel_map: true
#    observation_sources:  realsense_scan_sensorB
#    realsense_scan_sensorB:
#        data_type: PointCloud2
#        topic: /ransac_nogroundPoint
# #       marking: true
# #       clearing: true
#        inf_is_valid: true
#        min_obstacle_height: 0.015
#        max_obstacle_height: 0.8

#sonar_layer: 
#    clear_threshold: 0.2 #0.49
#    mark_threshold: 0.8 #0.98
#    topics: ["/sonar1", "/sonar2", "/sonar3"]
#    clear_on_max_reading: true 
    

global_inflation_layer:                       #膨胀层，用于在障碍物外标记一层危险区域，在路径规划时需要避开该危险区域
    enabled: true
    cost_scaling_factor: 4.0 #2.58 #5 #2.58 #2.0                              # default 10.0
    inflation_radius:  0.15  #1.75 #0.55 #0.46  #0.2   # default 0.55   设置障碍物的膨胀半径(通常设置为机器人底盘直径大小) 
local_inflation_layer:              #膨胀层，用于在障碍物外标记一层危险区域，在路径规划时需要避开该危险区域
    enabled: true
    cost_scaling_factor: 6.0 #10 #2.58 #2 #50 #2.58 #20 #2.58 #1.75 #2.8 # 5 #2.58 #5 #2.58  #5 #10 #2.58                               # default 10.0
    inflation_radius:  0.1 #0.5 #0.7 #0.15 #0.2 #1.75 #1.25 #0.5 #1.75 #0.23  #0.2                                   # default 0.55   设置障碍物的膨胀半径(通常设置为机器人底盘直径大小) 
#inflation_layer:                                         #膨胀层，用于在障碍物外标记一层危险区域，在路径规划时需要避开该危险区域
#    #enabled: true
#    #cost_scaling_factor: 60 #5 # 5 #2.58 #5 #2.58  #5 #10 #2.58                  # default 10.0
#    #inflation_radius:  0.3 #0.55 #1.75 #1.25 #0.5 #1.75 #0.23  #0.2           # default 0.55   设置障碍物的膨胀半径(通常设置为机器人底盘直径大小) 

static_layer:                                                #静态地图层，即SLAM中构建的地图层
    enabled: true
    map_topic: "/map"
    map_type: costmap                                         #地图类型





