local_costmap:
#  robot_radius: 0.23
#  footprint: [[-0.42,-0.32],[-0.42,0.32],[0.42,0.32],[0.42,-0.32]]
  global_frame:   map
  map_type: costmap
  robot_base_frame: base_link

  update_frequency:  5.0

  publish_frequency: 3.0

  static_map: false

  rolling_window: true

  width: 4.0
  height: 4.0
  resolution: 0.03
# inflation_radius: 0.2
  transform_tolerance: 0.5

  plugins:
#   - {name: camera_layer,            type: "costmap_2d::VoxelLayer"}
   - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
#   - {name: sonar_layer, type: "range_sensor_layer::RangeSensorLayer"}
   - {name: local_inflation_layer, type: "costmap_2d::InflationLayer"}

 
 
