TrajectoryPlannerROS:
  acc_lim_x: 2.5
  max_vel_x: 1.4
  min_vel_x: 0.3
  escape_vel: -0.4

  acc_lim_theta: 2.5
  max_vel_theta: 1.2
  min_vel_theta: -1.2
  min_in_place_vel_theta: 0.2

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1

  vx_samples: 10
  vtheta_samples: 20
  sim_time: 1.0

  sim_granularity: 0.08
  controller_frequency: 10

  path_distance_bias: 0.6
  goal_distance_bias: 0.8
  meter_scoring: true
  dwa: false
  holonomic_robot: false



