obstacle_range: 2.0 # 用于障碍物探测，比如: 值为 3.0，意味着检测到距离小于 3 米的障碍物时，就会引入代价地图
raytrace_range: 2.0
#robot_radius: 0.23
#footprint: [[0.0, -0.325],[0.0, 0.325],[0.55, 0.325],[0.55, -0.325]]
footprint: [[-0.4, -0.29],[-0.4, 0.29],[0.4, 0.29],[0.4, -0.29]]

#inflation_radius: 0.1
#min_obstacle_height: 0.0

resolution: 0.01

#laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: topic_name, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: particlecloud, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}





