obstacle_range: 2.0
raytrace_range: 3.0 
#robot_radius: 0.3  
footprint: [[0.5,0.4], [0.5,-0.4], [-0.5,-0.4], [-0.5,0.4]]  #M:[[0.3,0.3], [0.3,-0.3], [-0.3,-0.3], [-0.3,0.3]] Y:[[0.5,0.4], [0.5,-0.4], [-0.5,-0.4], [-0.5,0.4]]
inflation_radius: 0.4 #M:0.3 Y:0.4
max_obstacle_height: 0.8                                # default 2.0   描述障碍物的最大高度
min_obstacle_height: 0.03
observation_sources: scan  #realsense_scan_sensorB   #realsense_scan_sensorA
scan: {data_type: LaserScan, topic: /scan_filtered, marking: true, clearing: true, expected_update_rate: 0}  #filtered





