global_costmap:
  global_frame: map
#  robot_radius: 0.23
#footprint: [[-0.42,-0.32],[-0.42,0.32],[0.42,0.32],[0.42,-0.32]]
#  #map_type: costmap
  robot_base_frame: base_link

  update_frequency:  1.0

  publish_frequency: 1.0
  static_map: true
  rolling_window: false
  resolution: 0.03
  transform_tolerance: 1.0
  map_type: costmap
  
   
