
#footprint: [[-0.4, -0.29],[-0.4, 0.29],[0.4, 0.29],[0.4, -0.29]]
#footprint: [[-0.4, 0.3],[0, 0.5],[0.4, 0.3],[0.5, 0],[0.4, -0.3],[0, -0.5],[-0.4, -0.3],[-0.5, 0]]

map_type: costmap                                               #地图类型

obstacle_layer:                                                      #配置障碍物图层
  enabled: true                                                       #是否启用
  combination_method: 1                                    # default 1  只能设置为0或1，用来更新地图上的代价值，一般设置为1
  track_unknown_space: true                               # default false
  obstacle_range: 2.5                                           # default 2.5   检测障碍物的最大范围
  raytrace_range: 3.0                                           # default 3.0   检测自由空间的最大范围
  max_obstacle_height: 0.6                                 # default 2.0   描述障碍物的最大高度
  min_obstacle_height: 0.0                                 # 描述障碍物的最小高度
  observation_sources: laser_scan_sensor         # 代价地图需要关注的传感器信息
  laser_scan_sensor: {
    sensor_frame: laser,                                       # 激光雷达传感器的坐标系名称;
    topic: scan,                                                         # 该激光雷达发布的话题名;
    data_type: LaserScan,                                   # 激光雷达数据类型;
    marking: true,                                              # 是否使用该传感器来标记障碍物;
    clearing: true,                                              # 是否使用该传感器来清除障碍物标记为自由空间;
  }

inflation_layer:                                               #膨胀层，用于在障碍物外标记一层危险区域，在路径规划时需要避开该危险区域
  enabled: true
  cost_scaling_factor: 5.0                              # default 10.0
  inflation_radius: 0.0  #0.2                                   # default 0.55   设置障碍物的膨胀半径(通常设置为机器人底盘直径大小) 

static_layer:                                                #静态地图层，即SLAM中构建的地图层
  enabled: true





