global_costmap:
  global_frame: map                                           #全局代价地图需要在哪个坐标系下运行
  robot_base_frame: base_link                           #在全局代价地图中机器人本体的基坐标系，就是机器人上的根坐标系
  update_frequency: 1.0        #3.0                              #全局代价地图更新频率(单位:Hz），一般全局代价地图更新频率设置的比较小；
  publish_frequency: 0.5                                     #全局代价地图发布的频率(单位:Hz）
  #static_map: true                                               #配置是否使用map_server提供的地图来初始化;如果不需要使用已有的地图或者map_server，最好设置为false；
  rolling_window: false                                       #是否在机器人移动过程中需要滚动窗口，始终保持机器人在当前窗口中心位置
  transform_tolerance: 0.5                                 #坐标系间的转换可以忍受的最大延时
  #inflation_radius: 0.3
  plugins:                                                           #在global_costmap中使用下面三个插件来融合三个不同图层
  - {name: static_layer,    type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  
