base_global_planner: "global_planner/GlobalPlanner"            # 指定用于move_base的全局规划器插件名称
#base_local_planner: "dwa_local_planner/DWAPlannerROS"    # 指定用于move_base的局部规划器名称
base_local_planner: "base_local_planner/TrajectoryPlannerROS"

shutdown_costmap: false        # default false  当move_base在不活动状态时,是否关掉costmap

controller_frequency: 5.0       # default 20.0   向底盘控制移动话题cmd_vel发送命令的频率
controller_patience: 3.0        # default 15.0   在空间清理操作执行前,控制器花多长时间等有效控制指令下发

planner_frequency: 2.0    #0.5      # default 0.0    全局规划操作的执行频率(Hz)。如果频率设置为0.0，则仅当收到新目标或局部规划器报告其路径堵塞时，才会重新执行规划操作。
planner_patience: 5.0           # default 5.0    在空间清理操作执行前,留给规划器多长时间(s)来找出一条有效规划

conservative_reset_dist: 0.5    # default 3.0    尝试清除地图中的空间时，距离机器人几米远的障碍将会从代价地图清除。注意，仅当默认恢复行为用于move_base时，才使用此参数。

oscillation_timeout: 10.0       # default 0.0    执行恢复行为之前允许振荡的秒数
oscillation_distance: 0.2       # default 0.5    机器人必须移动多米才能被视为没有振动

recovery_behavior_enabled: true # default true   是否启用move_base恢复行为以尝试清除空间。
clearing_rotation_allowed: true  # default true   确定在尝试清理空间时机器人是否将尝试就地旋转。 注意：仅当使用默认恢复行为时才使用此参数，这意味着用户尚未将recovery_behaviors参数设置为任何自定义设置。
max_planning_retries: -1.0        # default -1     执行恢复行为之前允许多少次计划重试。值-1.0对应于无限次重试。
